README.rdoc

Changed distintive to distinctive

Correct the spelling of distinctive

---

.gitignore
README.md
moab-versioning.gemspec
spec/spec_helper.rb

- add coveralls
- add `.pry_history` to `.gitignore`
Resolves #23

Add coveralls

---

README.md

Add documentation for how to make a Moab::FileInventory

---

README.md

changed 1 variable name that was there from copy pasting

fixed current_version to object_size_in_bytes

---

README.md

- usage for Moab validation
connects #82

Update README usage with well formed moab

---

lib/stanford/storage_object_validator.rb

i felt bad nagging about this since PR #80 was totally mergeable, and since it was quicker for me to just put up a follow on PR instead of asking for more changes.

replace append-and-flatten two step with a single concat

---

README.md

Document Stanford::StorageOjbectValidator in README

---

lib/moab/storage_object_validator.rb
spec/unit_tests/moab/storage_object_validator_spec.rb

remove .keep from class and only use it in rspec tests

---

README.md

This is quick update to the README because I created some wiki pages from  https://docs.google.com/document/d/14p3EMRHjoo_osOCRgwaIGCoACUr1yoZmSbJ0fXwGWAk  (with permission, of course).  
This adds some developer-level documentation.

update readme now that we have wikis

---

spec/unit_tests/moab/file_group_difference_spec.rb

~~[WIP: merge PR #130 first and this should pass rubocop]~~
a re-working of the specs for #compare_file_groups in file_group_difference
Connects to #6

unit_tests/moab/file_group_diff_spec: #compare_file_groups refactor

---

lib/moab/storage_object_validator.rb

Especially single-element arrays.
Add a couple lines of detailed YARD.

Building arrays is not as hard as this code seemed to think

---

.rubocop_todo.yml
lib/moab/config.rb
lib/moab/file_signature.rb
spec/unit_tests/moab/bagger_spec.rb
spec/unit_tests/moab/deposit_bag_validator_spec.rb
spec/unit_tests/moab/file_group_spec.rb
spec/unit_tests/moab/file_signature_spec.rb
spec/unit_tests/moab/signature_catalog_spec.rb
spec/unit_tests/moab/storage_object_spec.rb
spec/unit_tests/moab/storage_object_version_spec.rb
spec/unit_tests/moab/storage_repository_spec.rb
spec/unit_tests/stanford/content_inventory_spec.rb

Properly submitted for review this time, the configurability of algorithms being checked by `FileSignature`
Fixes #142

Redo algo config

---

lib/moab/file_signature.rb

Also, classes should use their accessors instead of constantly referencing the instance vars.
Split from rubocop-related cleanup in #137

Building hashes is not as hard as this code seemed to think it is

---

lib/moab/storage_repository.rb
lib/stanford/storage_repository.rb

Correct type on two incorrect YARD statements

---

.github/workflows/ruby.yml

Switch from TravisCI to GH Actions

---

.rubocop.yml
lib/moab/storage_repository.rb
lib/moab/storage_services.rb
lib/serializer/serializable.rb
spec/features/stanford/content_metadata_read_spec.rb
spec/unit_tests/moab/file_inventory_spec.rb

Remove useless assignments

---

.github/workflows/ruby.yml
README.md

Update default branch references from master to main

---

README.md

to clarify some hard won knowledge about where checksum validation actually occurs.

README:  validation script now shows which validation happens where and is formatted better

---

README.md

follow on from https://github.com/sul-dlss/moab-versioning/pull/177, made more sense to merge and submit this than to go back and forth on that
readme only

nitpicky script message touchup

---

README.md

better accuracy is ... better.

README: more accurate comment about checksum validation in full script

---

Gemfile.lock
lib/moab/storage_object.rb
lib/moab/storage_object_version.rb
spec/unit_tests/moab/storage_object_spec.rb
spec/unit_tests/moab/storage_object_version_spec.rb

Fixes #200
This allows us to do a normal move operation rather than using links.
Test suite

Expose the use_links parameter on ingest_bag

---

lib/moab/storage_services.rb
lib/stanford/storage_services.rb
spec/unit_tests/moab/storage_services_spec.rb
spec/unit_tests/stanford/storage_services_spec.rb

Fixes #189 
This wraps the class variable in a class method for easier readability and refactoring, and tests that the respective `StorageRepository` for each is only instantiated once.

comment about thread safety on class var in `StorageServices` classes, additional related test

---

spec/features/storage/ingest_spec.rb

improve ingest_spec towards contemporary practices.  Part of #194.

ingest_spec: updated towards conventions

---

Gemfile.lock

Gemfile.lock updated with development gem pry-byebug

---

.rubocop.yml
Gemfile.lock

because I haven't yet figured out how to make the dep update PRs for our gems commit Gemfile.lock

Gemfile lock updated.

---

.rubocop.yml
spec/unit_tests/moab/file_group_difference_spec.rb
spec/unit_tests/moab/file_group_spec.rb
spec/unit_tests/moab/file_inventory_difference_spec.rb
spec/unit_tests/moab/file_inventory_spec.rb
spec/unit_tests/moab/file_signature_spec.rb
spec/unit_tests/moab/signature_catalog_spec.rb

rubocop gets new cops

---

moab-versioning.gemspec

To get the `new reset_bag()` behavior out there to hopefully avoid getting these Honeybadger errors:
https://app.honeybadger.io/projects/50568/faults/121528122
Unit tests

Bump version to 6.1.1
