.rubocop.yml
spec/spec_config.rb

also make spec_config more readable

rubocop - turn off string literals

---

spec/unit_tests/stanford/active_fedora_object_spec.rb
spec/unit_tests/stanford/content_inventory_spec.rb
spec/unit_tests/stanford/dor_metadata_spec.rb
spec/unit_tests/stanford/storage_repository_spec.rb
spec/unit_tests/stanford/storage_services_spec.rb

spec/unit_tests/stanford: remove cruft (inspired by rubocop)

---

README.md
lib/moab/storage_repository.rb
lib/moab/storage_services.rb
spec/unit_tests/moab/storage_repository_spec.rb
spec/unit_tests/moab/storage_services_spec.rb

- Add object size method to `Moab::StorageRepository`
- Updated README w/ usage
closes #21

Add object size method to gem

---

spec/unit_tests/moab/file_manifestation_spec.rb

unit_tests/moab/file_manifestation_spec: remove cruft

---

lib/moab/file_signature.rb
spec/unit_tests/moab/file_signature_spec.rb

This PR also changes the code to raise a more specific error in one context.  I can break that out into a separate PR (it is already a separate commit). …

unit_tests/moab/file_signature_spec: remove cruft

---

spec/unit_tests/moab/signature_catalog_entry_spec.rb

- no useful tests removed (some pointless ones have been removed)
- removes specs that are useless (e.g. that setting an attribute value means you can retrieve the attribute value; that instantiating an object returns an instance of the object)
etc.

unit_tests/moab/signature_catalog_entry_spec: remove cruft

---

spec/unit_tests/moab/file_group_difference_subset_spec.rb

unit_tests/moab/file_group_diff_subset_spec: remove cruft

---

spec/unit_tests/moab/file_instance_spec.rb

unit_tests/moab/file_instance_spec: remove cruft

---

lib/moab/file_inventory.rb
spec/unit_tests/moab/file_inventory_spec.rb

unit_tests/moab/file_inventory_spec: remove cruft

---

spec/unit_tests/moab/file_inventory_difference_spec.rb

unit_tests/moab/file_inventory_difference_spec: remove cruft

---

.travis.yml
spec/spec_helper.rb

- spec_helper:  
- don't report coverage in spec files
- only report coverage once per travis build (not for each ruby version)
- cleaned up some cruft not needed or no longer needed
- .travis.yml:  added ruby 2.4.2;  added explicit script so we can run `bundle exec coverall push` if we want to check coverage for a build outside of travis
Note that coverage decrease is because we no longer count spec files.

code coverage no longer includes spec files

---

moab-versioning.gemspec

Fixes #39 
Version 1.3.6 of RubyGems is from February 2010. It seems that we can safely remove this version dependency.

Use any version of RubyGems.

---

README.md

README doesn't refer to druids in Moab docs

---

.rubocop.yml
lib/stanford/storage_object_validator.rb
spec/unit_tests/stanford/storage_object_validator_spec.rb

- Only run identify_druid if we know there is a manifest directory / correctly constructed Moab
- added correct test to spec/unit_tests/stanford

Run identify_druid only if we know there is a moab with the correct dirs

---

lib/moab/storage_object_validator.rb

Small refactoring inspired by #99 (use Enum.detect when checking for subdirs).
- remove misleading private #sub_dirs method, which was effectively an alias for the more aptly named #directory_entries method
- use John's suggestion of Enum.detect when checking for subdirs of `content` and `metadata`, but use a more elegant approach with #contains_sub_dir? 
- remove unnec. TODO
- reword another comment
resolves #99

Use detect

---

spec/unit_tests/moab/file_group_difference_spec.rb

Breaking up the horrid PR #50 in favor of smaller, easier to review PRs.  If this one is too big, let me know and I'll make it smaller.
I strongly recommend you review this commit by commit;  I tried to make the commits simple.  You may find the unifed view works better for reviewing some commits, the split view for others.
- removes specs that are useless  (e.g. that setting an attribute value means you can …

File group diff spec first

---

spec/unit_tests/moab/file_group_difference_spec.rb

I strongly recommend you review this commit by commit; I tried to make the commits simple. You may find the unifed view works better for reviewing some commits, the split view for others.
The first commit focuses on "within line" readability and rocket hashes.
The second commit is simple, but splitting it out makes it a lot easier to look at the diff for the first commit.
- no useful tests removed (some pointless ones have been removed)
connects to #6

File group diff spec - second

---

lib/moab.rb
lib/moab/bagger.rb
lib/moab/file_inventory.rb

THIS is why we have these three checksums everywhere.  Thought I would make it clearer.

declare DEFAULT_CHECKSUM_TYPES constant in Moab module and use it

---

spec/unit_tests/moab/file_group_difference_spec.rb

update the #tabulate_xxx_files specs, fix 2 typos, and add a note that the specs are ordered.
Connects to #6

File group diff spec five

---

lib/moab/file_signature.rb
spec/unit_tests/moab/file_signature_spec.rb

I'm putting in the PR now so that work can proceed against the correct method.  We can deal with the system configurability secondarily.
Note: the initializer is removed here, because it *does nothing*. If all a method does is call `super` with the same args, it is better for it not to exist.
Connects to sul-dlss/preservation_catalog#642

Selectable checksums and matching tests

---

.rubocop_todo.yml
lib/moab/storage_object_validator.rb
lib/moab/storage_object_version.rb
lib/moab/verification_result.rb

Subsume two single-line single-use methods.
Utilize guard clauses and the return value of `.concat` (and other methods).

Reduce indirection

---

lib/moab/config.rb
lib/moab/file_signature.rb
spec/unit_tests/moab/file_signature_spec.rb

This reverts commit ed5c3a72bd860c10ff98be016c42b447123f1a28.

Revert "Use Moab::Configure to set checkums active in FileSignature"

---

moab-versioning.gemspec

Obviously we don't debug on Travis and this requirement actually breaks builds at install-time, like:
https://travis-ci.org/sul-dlss/moab-versioning/jobs/364883575#L585
Error is: `byebug requires Ruby version >= 2.2.0`
Ideally we can eventually drop ruby 2.2 support, but this is a reasonable measure anyway.

Don't require pry-byebug on CI

---

lib/moab/config.rb
lib/moab/file_group.rb
lib/moab/file_group_difference.rb
lib/moab/file_group_difference_subset.rb
lib/moab/file_instance.rb
lib/moab/file_instance_difference.rb
lib/moab/file_inventory.rb
lib/moab/file_inventory_difference.rb
lib/moab/file_manifestation.rb
lib/moab/file_signature.rb
lib/moab/signature_catalog.rb
lib/moab/signature_catalog_entry.rb
lib/moab/storage_object.rb
lib/moab/storage_object_validator.rb
lib/moab/storage_object_version.rb
lib/moab/storage_repository.rb
lib/moab/storage_services.rb
lib/moab/utc_time.rb
lib/moab/verification_result.rb
lib/moab/version_metadata.rb
lib/moab/version_metadata_entry.rb
lib/moab/version_metadata_event.rb
lib/stanford/active_fedora_object.rb
lib/stanford/content_inventory.rb
lib/stanford/dor_metadata.rb
lib/stanford/storage_object_validator.rb
lib/stanford/storage_repository.rb
lib/stanford/storage_services.rb

As revealed by `rspec --warnings`. This was an anti-pattern for a gem component to need to require the base namespace class because literally all consumers are already doing:
```
require 'moab'
```
or
```
require 'moab/stanford'
```
So the base class/namespace will always already be loaded before any subclass is invoked.

Stop circular dependency loading

---

lib/moab/storage_object_validator.rb
spec/unit_tests/moab/storage_object_validator_spec.rb
spec/unit_tests/stanford/storage_object_validator_spec.rb

An example log output from seeding
```
[2017-11-22T04:55:11.113017 #25241] ERROR -- :  .............. 
Invalid moab, validation errors: ["Should only contain files, but directories were present in the content directory"]
```
So this PR will give us more details on which directory was present and is not supposed to be there.
- allow `error_code_msg` to take multiple args other than `addl`
- `METADATA_SUB_DIRS_DETECTED` and `CONTENT_SUB_DIRS_DETECTED`changed `addl` to `version` and added a `dir` variable to tell us the offending directory in logs.
closes #106

Include offending dir name to pertaining error codes

---

.github/pull_request_template.md
lib/moab/bagger.rb
lib/moab/exceptions.rb
lib/moab/file_group.rb
lib/moab/file_signature.rb
lib/moab/signature_catalog.rb
lib/moab/storage_object.rb
lib/moab/storage_object_version.rb
lib/moab/storage_repository.rb
lib/moab/utc_time.rb
lib/serializer/serializable.rb
lib/stanford/content_inventory.rb
lib/stanford/storage_repository.rb
spec/unit_tests/moab/bagger_spec.rb
spec/unit_tests/moab/file_group_spec.rb
spec/unit_tests/moab/file_signature_spec.rb
spec/unit_tests/moab/storage_object_spec.rb
spec/unit_tests/moab/storage_repository_spec.rb
spec/unit_tests/moab/utc_time_spec.rb
spec/unit_tests/serializer/serializable_spec.rb
spec/unit_tests/stanford/content_inventory_spec.rb
spec/unit_tests/stanford/storage_repository_spec.rb

Closes #159
To fix a kludge in preservation_catalog (see https://github.com/sul-dlss/preservation_catalog/pull/1207/files) that would become more onerous as prescat gets more API functionality to replace sdr-services-app.
N/A

add InvalidSuriSyntaxError, MoabRuntimeError, MoabStandardError

---

lib/moab.rb
lib/moab/config.rb
moab-versioning.gemspec

It's easy enough to maintain our own static config.  The confstruct gem is no longer maintained.
n/a

Drop dependency on confstruct

---

README.md

This includes a known-good script that will completely validate a given Druid in Stanford's environment.
The existing example in Readme.md doesn't fully illustrate how to check a Moab in Stanford's environment.
Checked against both known-good and broken druids.
Readme.md

Update Readme.md to expand examples

---

.rubocop.yml
spec/unit_tests/moab/bagger_spec.rb
spec/unit_tests/moab/file_group_difference_spec.rb
spec/unit_tests/moab/file_instance_spec.rb
spec/unit_tests/moab/file_inventory_difference_spec.rb
spec/unit_tests/moab/file_inventory_spec.rb
spec/unit_tests/moab/file_manifestation_spec.rb
spec/unit_tests/moab/file_signature_spec.rb
spec/unit_tests/moab/storage_object_spec.rb
spec/unit_tests/moab/storage_object_validator_spec.rb
spec/unit_tests/moab/storage_object_version_spec.rb
spec/unit_tests/moab/utc_time_spec.rb
spec/unit_tests/moab/verification_result_spec.rb
spec/unit_tests/serializer/manifest_spec.rb
spec/unit_tests/serializer/serializable_spec.rb
spec/unit_tests/stanford/content_inventory_spec.rb

Enables new cops to quiet warnings, autocorrect to fix correctable issues.

Enable new cops and autocorrect

---

.rubocop.yml
spec/unit_tests/moab/storage_object_spec.rb

There is a small difference between the data output on circle and locally, so this line is required to allow the tests to pass locally and in circle (line 156).
This highlights a smell that should be addressed as part of #194 

Fix minor issue/difference between circle tests and local

---

Gemfile.lock

This updated the Gemfile.lock. I supect the previous version was created with `CI="true"` in the environment. https://github.com/sul-dlss/moab-versioning/blob/main/moab-versioning.gemspec#L26

Gemfile.lock updated - Run bundle install

---

Gemfile.lock
lib/moab/storage_object_version.rb

Performance
techmd-prod
It reduced listing files for an item with 421 files from 162 seconds to 1.23 seconds. Verified that the results were the same.

Performance improvement in storage_object_version.

---

spec/unit_tests/moab/bagger_spec.rb

One small step towards better spec practices.  Part of #194.

bagger_spec: remove instance variables

---

spec/unit_tests/moab/storage_object_version_spec.rb

storage_object_version_spec: updated to current rspec conventions. Part of https://github.com/sul-dlss/moab-versioning/issues/194.

storage_object_version_spec: updated to current rspec conventions

---

spec/unit_tests/moab/signature_catalog_spec.rb

signature_catalog_spec: updated to current rspec conventions.  Part of #194.

signature_catalog_spec: updated to current rspec conventions

---

lib/moab/file_group.rb
spec/unit_tests/moab/file_group_spec.rb

So this spec requires less cognitive load
Part of #194.

file_group_spec: update to current rspec conventions

---

spec/spec_helper.rb
spec/unit_tests/moab/storage_object_validator_spec.rb
spec/unit_tests/stanford/storage_object_validator_spec.rb

One small step towards better spec practices.  Part of #194.
Removes this noise from spec running output:
(below is only 1/2 of the noise)
```
/Users/ndushay/sul-dlss-github/moab-versioning/spec/unit_tests/stanford/storage_object_validator_spec.rb:10: warning: already initialized constant Moab::StorageObjectValidator::IMPLICIT_DIRS
/Users/ndushay/sul-dlss-github/moab-versioning/spec/unit_tests/moab/storage_object_validator_spec.rb:12: warning: previous definition of IMPLICIT_DIRS was here
/Users/ndushay/sul-dlss-github/moab-versioning/spec/unit_tests/stanford/storage_object_validator_spec.rb:12: warning: already initialized constant Moab::StorageObjectValidator::IMPLICIT_DIRS
/Users/ndushay/sul-dlss-github/moab-versioning/spec/unit_tests/stanford/storage_object_validator_spec.rb:10: …
```

silence spec warnings for already initialized constant

---

spec/features/differences/version_compare_spec.rb
spec/unit_tests/moab/file_group_difference_spec.rb
spec/unit_tests/moab/file_inventory_difference_spec.rb
spec/unit_tests/moab/file_inventory_spec.rb
spec/unit_tests/moab/signature_catalog_spec.rb
spec/unit_tests/moab/storage_object_version_spec.rb
spec/unit_tests/moab/storage_services_spec.rb
spec/unit_tests/stanford/content_inventory_spec.rb
spec/unit_tests/stanford/storage_repository_spec.rb

Let's call it what it is:  OCD.

use spec_helper constants for test druid

---

.rubocop.yml

because we haven't as a team decided to turn on 
```
AllCops:
NewCops: enable
```
as it could burden the FR unduly ?

rubocop: add new rule to appease our rubocop overlords

---

lib/moab/storage_repository.rb
spec/unit_tests/moab/storage_repository_spec.rb

So this spec requires less cognitive load.
Part of #194

storage_repository_spec: update to current rspec conventions

---

spec/features/inventory/write_inventory_xml_spec.rb
spec/features/serializer/write_xml_spec.rb
spec/features/stanford/content_metadata_write_spec.rb
spec/spec_helper.rb
spec/unit_tests/moab/file_group_difference_spec.rb
spec/unit_tests/moab/storage_object_spec.rb
spec/unit_tests/moab/storage_services_spec.rb
spec/unit_tests/stanford/content_inventory_spec.rb
spec/unit_tests/stanford/storage_services_spec.rb

So rspec output shows the actual difference in the xml, rather than just "expected false, but it was true" 

specs: get more informative output from equivalent-xml gem

---

moab-versioning.gemspec

we run at least ruby 3.0 everywhere

update required_ruby_version to 3.0

---

spec/features/differences/version_compare_spec.rb

remove vestigial comment

---

Gemfile.lock
moab-versioning.gemspec

Without this change, pulling `main` and running `bundle install` winds up causing changes to `Gemfile.lock`; namely, adding `pry-byebug` and its dependencies. That is jarring and it is not clear that the reason we added this check five years ago is something we still care about.
The original issue being worked around is TravisCI failing to add pry-byebug to the bundle because it did not support Ruby 2.2: https://github.com/sul-dlss/moab-versioning/pull/149
I suspect the reason this dep is left out of the lockfile is that `ENV['CI']` is `true` when generating weekly dep update PRs on Jenkins.
If this messes up Monday's dep update for moab-versioning, I'm the FR 🤷🏻‍♂️ 
CI

Keep pry-byebug as a dev dependency even in CI

---

.rubocop.yml
Rakefile
spec/unit_tests/moab/storage_object_spec.rb

This commit contains some spring cleaning in order to help this gem keep pace with our current practices.
Includes:
* Add missing Rubocop rules
* Update Rakefile to remove outdated cruft and unnecessary setup / tasks
* Change `raise_error` usage in a spec in response to an RSpec warning
CI + ran `rake` locally

Update Rubocop, Rake, and RSpec usage

---

lib/moab/storage_object_validator.rb
spec/unit_tests/moab/storage_object_validator_spec.rb
spec/unit_tests/stanford/storage_object_validator_spec.rb

Fixes #258
Now that SDR is beginning to allow users to upload content with path information, some paths within deposited items will contain directories named e.g. `data` or `content` or `metadata`. The moab-versioning gem flags these items as having forbidden content subdirectories. This is *not* part of the Moab specification, and we think this was some past attempt to prevent nested moab directory structures. We are now removing this consideration from the gem.
CI

Loosen validation of subdirectory names within content directory

---

lib/moab/file_group.rb
lib/moab/file_inventory_difference.rb
lib/moab/file_signature.rb
lib/stanford/content_inventory.rb

Fixes #266
This commit changes the `FileGroup`, `FileInventoryDifference`, `FileSignature`, and `ContentInventory` classes in order to reduce performance bottlenecks when diffing moabs with voluminous content metadata. (See #266 for a breakdown of the profiling results and methodology.)
Generally, the changes were intended to avoid unnecessary mutations, to make more judicious use of iterators (more important when dealing with extremely large collections!), and to cut down on the sheer number of method invocations within operations being called millions of times for a large test object. Each of these methods were targeted based on [profiling analysis](https://github.com/sul-dlss/moab-versioning/issues/266#issuecomment-1406812866).
Specific changes include:
* `FileGroup#path_hash_subset`
* …

Add performance hacks to FileGroup and FileSignature classes

---

.rubocop.yml
Gemfile.lock
spec/unit_tests/moab/file_group_spec.rb
spec/unit_tests/serializer/serializable_spec.rb

OCD for our neglected gem children.

add new rubocops and tweaks

---

lib/stanford/storage_services.rb

See https://github.com/sul-dlss/dor-services-app/pull/4492  ... adds a parallel code comment indicating that we this method is re-implemented in DSA

add code comment
